/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2022-03-29 15:05:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>\r\n");
      out.write("        Login\r\n");
      out.write("    </title>\r\n");
      out.write("    <STYLE>\r\n");
      out.write("        #body{\r\n");
      out.write("            background-color: #202020;\r\n");
      out.write("            color: orange;\r\n");
      out.write("            font-family: 'JetBrains Mono', monospace;\r\n");
      out.write("        }\r\n");
      out.write("        #menu{\r\n");
      out.write("            margin-left: 27%;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            font-size: larger;\r\n");
      out.write("        }\r\n");
      out.write("        #signup{\r\n");
      out.write("            background-color: #202020;\r\n");
      out.write("            border: 2px solid #404040;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            width: 360px;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"]{\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            margin-left: 42%;\r\n");
      out.write("            font-family: 'JetBrains Mono', monospace;\r\n");
      out.write("        }\r\n");
      out.write("        input{\r\n");
      out.write("            background-color:#404040;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"radio\"]{\r\n");
      out.write("            accent-color:green;\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        #login{\r\n");
      out.write("            background-color: #202020;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            border: 2px solid #404040;\r\n");
      out.write("        }\r\n");
      out.write("        .a{\r\n");
      out.write("            margin-left: 30px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("        .header{\r\n");
      out.write("            margin-left: 40%;\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            color: orange;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .menuWriting{\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color:green;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </STYLE>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id = \"body\">\r\n");
      out.write("    <DIV id = \"content\">\r\n");
      out.write("       <b height = \"120\" class=\"header\">Java Jungle</b>\r\n");
      out.write("    <DIV ID = \"menu\">\r\n");
      out.write("        <DIV ID = \"login\">\r\n");
      out.write("            <p class=\"menuWriting\">Login:</p>\r\n");
      out.write("            <form method=\"post\" action=\"login\">\r\n");
      out.write("                <label for=\"email\">E-mail: </label>\r\n");
      out.write("                <input type=\"email\" name=\"email\" id=\"email\"><br>\r\n");
      out.write("                <label for=\"pword\">Password: </label>\r\n");
      out.write("                <input type=\"password\" name=\"pword\" id=\"pword\"><br>\r\n");
      out.write("                <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </DIV>\r\n");
      out.write("        <DIV ID = \"signup\">\r\n");
      out.write("            <form method=\"post\" action=\"signup\">\r\n");
      out.write("                <p class=\"menuWriting\">Sign-up: </p>\r\n");
      out.write("                <label for=\"fname\">Firstname: </label>\r\n");
      out.write("                <input type=\"text\" id=\"fname\" name=\"fname\"><br>\r\n");
      out.write("                <label for=\"lname\">Lastname: </label>\r\n");
      out.write("                <input type=\"text\" id=\"lname\" name=\"lname\"><br>\r\n");
      out.write("                <label for=\"email\">E-mail: </label>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\"><br>\r\n");
      out.write("                <label for=\"pword\">Password: </label>\r\n");
      out.write("                <input type=\"password\" id=\"pword\" name=\"pword\" class=\"invalid\"><br>\r\n");
      out.write("                <input type=\"radio\" name=\"button_clicked\" value=\"student\" class=\"a\" checked>Student</button>\r\n");
      out.write("                <p class=\"a\">OR</p>\r\n");
      out.write("                <input type=\"radio\" name=\"button_clicked\" value=\"teacher\" class=\"a\">Teacher</button><br>\r\n");
      out.write("                <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </DIV>\r\n");
      out.write("    </DIV>\r\n");
      out.write("        <canvas id=\"myCanvas\" width=\"700\" height=\"650\"></canvas>\r\n");
      out.write("    </DIV>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
